config/routes.rb
Rails.application.routes.draw do
  devise_for :artists
  root to: "homes#index"
  resources :artists, only: [:index, :edit, :update, :show]
  resources :arts, only: [:new, :create, :index, :destroy]
  resources :matchings, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :arttype
  belongs_to_active_hash :arttouch

  attachment :image
  belongs_to :artist

  with_options presence: true do
    validates :image
    validates :arttype_id
    validates :arttouch_id
  end

  with_options numericality: { other_than: 1, message: 'を選択して下さい' } do
    validates :arttype_id
    validates :arttouch_id
  end
end

app/models/artist.rb
class Artist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :arttype
  belongs_to_active_hash :arttouch
  belongs_to_active_hash :price

  has_many :arts, dependent: :destroy
  attachment :profile_image

  validates :email, uniqueness: { case_sensitive: true }
  validates :password_confirmation, :password, confirmation: true

  with_options presence: true do
    validates :name
    validates :job_request
    validates :arttype_id
    validates :arttouch_id
    validates :profile
    validates :price_id
  end

  with_options numericality: { other_than: 1, message: 'を選択して下さい' } do
    validates :arttype_id
    validates :arttouch_id
    validates :price_id
  end
end

app/models/arttouch.rb
class Arttouch < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'あったか' },
    { id: 3, name: 'くっきり' }
  ]

  include ActiveHash::Associations
  has_many :artists
  belongs_to :art
end

app/models/arttype.rb
class Arttype < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'リアルテイスト' },
    { id: 3, name: 'ポップ' }
  ]

  include ActiveHash::Associations
  has_many :artists
  belongs_to :art
end

app/models/price.rb
class Price < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '要相談' },
    { id: 3, name: '1人500円' },
    { id: 4, name: '1人1000円' },
    { id: 6, name: '1人2000円' },
    { id: 7, name: '1人3000円' },
    { id: 8, name: '1人5000円' }
  ]

  include ActiveHash::Associations
  has_many :artists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(_resource)
    artist_path(current_artist)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :job_request, :arttype_id, :arttouch_id, :profile, :price_id, :line, :twitter])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_artist!, only: :edit
  before_action :set_id, only: [:edit, :update]
  before_action :move_to_home, only: :edit

  def index
    @artists = Artist.all
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to aciton: :edit
    else
      render :edit
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :email, :job_request, :arttype_id, :arttouch_id, :profile, :price_id, :line, :twitter, :profile_image)
  end

  def set_id
    @artist = Artist.find(params[:id])
  end

  def move_to_home
    redirect_to root_path unless current_artist.id == @artist.id
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :authenticate_artist!, except: :index

  def new
    @art = Art.new
    @arts = Art.includes(:artist).order('created_at DESC')
  end

  def create
    @art = Art.create(art_params)
    if @art.save
      redirect_to action: :new
    else
      @arts = Art.includes(:artist).order('created_at DESC')
      render :new
    end
  end

  def index
    @arts = Art.includes(:artist).order('created_at DESC')
  end

  def destroy
    art = Art.find(params[:id])
    art.destroy
    redirect_to action: :new
  end

  private

  def art_params
    params.require(:art).permit(:image, :arttype_id, :arttouch_id).merge(artist_id: current_artist.id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/matchings_controller.rb
class MatchingsController < ApplicationController
  def index
    @arts = Art.includes(:artist)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/matchings_helper.rb
module MatchingsHelper
end

app/views/artists/edit.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        登録情報の編集
      </h1>
      <h2 class="subtitle">
         Welcome great caricature artist!
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <%= form_with model: current_artist, url: artist_path, local: true do |f| %>
        <%= render 'shared/error_messages', model: @artist %>
          <div class="field">
            <%= f.label :name, class: "label" %>
            <p class="control has-icons-left">
              <%= f.text_field :name, class: "input is-success" %>
              <span class="icon is-small is-left">
                <i class="fas fa-user"></i>
              </span>
            </p>
          </div>

          <div class="field">
            <%= f.label :email, class: "label" %>
            <p class="control has-icons-left">
              <%= f.email_field :email, class: "input is-success" %>
              <span class="icon is-small is-left">
                <i class="fas fa-envelope"></i>
              </span>
            </p>
          </div>

          <div class="field">
            <%= f.label :profile, class: "label" %>
            <%= f.text_area :profile, class: "textarea is-success" %>
          </div>

          <div class="field">
            <%= f.label :job_request, "仕事の依頼方法", class: "label" %>
            <%= f.text_area :job_request, class: "textarea is-success" %>
          </div>

          <div class="field">
            <%= f.label :line, "(任意)仕事依頼にLineを希望する方のみidを記入", class: "label" %>
            <p class="control has-icons-left">
              <%= f.text_field :line, class: "input is-success" %>
              <span class="icon is-small is-left">
                <i class="fab fa-line"></i>
              </span>
            </p>
          </div>

          <div class="field">
            <%= f.label :twitter, "(任意)仕事依頼にTwitterを希望する方のみユーザー名を記入", class: "label" %>
            <p class="control has-icons-left">
              <%= f.text_field :twitter, class: "input is-success" %>
              <span class="icon is-small is-left">
                <i class="fab fa-twitter-square"></i>
              </span>
            </p>
          </div>

          <div class="field is-grouped">
            <div class="control">
              <%= f.label :arttype_id, "得意な絵の種類", class: "label" %>
              <div class="select is-primary">
                <%= f.collection_select(:arttype_id, Arttype.all, :id, :name, {} )%>
              </div>
            </div>

            <div class="control">
              <%= f.label :arttouch_id, "得意タッチ", class: "label" %>
              <div class="select is-primary">
                <%= f.collection_select(:arttouch_id, Arttouch.all, :id, :name, {} )%>
              </div>
            </div>

            <div class="control">
              <%= f.label :price_id, "1枚の価格", class: "label" %>
              <div class="select is-primary">
                <%= f.collection_select(:price_id, Price.all, :id, :name, {} )%>
              </div>
            </div>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input is-success" %>
          </div>
        
          <div class="field is-grouped is-grouped-centered">
            <%= f.submit "更新", class: "button is-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/artists/index.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        似顔絵師さん一覧
      </h1>
      <h2 class="subtitle">
        I hope I'll have a close relationship with artists!
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @artists.each do |artist| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image is-1by1">
                  <%= link_to artist_path(artist.id) do %>
                    <%= attachment_image_tag artist, :profile_image, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title is-size-5"><%= link_to artist.name, artist_path(artist.id) %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/artists/show.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= "似顔絵師「#{@artist.name}」の詳細ページ/似顔絵作成依頼方法について" %>
      </h1>
      <h2 class="subtitle">
        I hope I'll have a close relationship with artists!
      </h2>
    </div>
  </div>
</section>

<div class="tile is-ancestor">
  <div class="tile is-vertical is-3">
    <div class="tile">
      <div class="tile is-parent">
        <article class="tile is-child notification is-white">
          <div class="content has-text-centered">          
            <h4 class="title"><%= "#{@artist.name}'s information!" %></h4>
            <figure class="image is-256x256 is-inline-block">
              <%= attachment_image_tag @artist, :profile_image, fallback: "no-image.png"%>
            </figure>
            <p>・得意な絵の種類  <i class="far fa-hand-point-right"></i>  <%= @artist.arttype.name %></p>
            <p>・得意な絵のタッチ  <i class="far fa-hand-point-right"></i>  <%= @artist.arttouch.name %></p>
            <p>・絵の価格  <i class="far fa-hand-point-right"></i>  <%= @artist.price.name %></p>
            <p>・依頼方法  <i class="far fa-hand-point-down"></i></p>
            <%= @artist.job_request %><br><br>
            <p>・プロフィール  <i class="far fa-hand-point-down"></i></p>
            <%= @artist.profile %><br><br>
            <p>・連絡先のリンクはこちら <i class="far fa-hand-point-down"></i></p>
              <a class="fas fa-envelope fa-3x" href="#"></a>
              <% if !@artist.line.empty? %>
                <a class="fab fa-line fa-3x" href="#"></a>
              <% end %>
              <% if !@artist.twitter.empty? %>
                <a class="fab fa-twitter-square fa-3x" href="#"></a>
              <% end %>
            </p>
          </div>
        </article>
      </div>
    </div>
  </div>
  <div class="tile is-parent">
    <article class="tile is-child notification is-white">
      <div class="content has-text-centered">
        <h4 class="title"><%= "#{@artist.name}'s arts!" %></h4>
      </div>
      <section class="section">
        <div class="container">
          <div class="columns is-multiline">
            <% @artist.arts.each do |art| %>
              <div class="column is-4">
                <div class="card">
                  <div class="card-content">
                    <div class="card-image">
                      <figure class="image is-1by1">
                        <%= attachment_image_tag art, :image %>
                      </figure>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </section>
    </article>
  </div>
</div>

app/views/arts/index.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        似顔絵一覧
      </h1>
      <h2 class="subtitle">
         I hope I'll have a close relationship with artists!
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @arts.each do |art| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image is-1by1">
                  <%= attachment_image_tag art, :image %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title is-size-5"><%= link_to art.artist.name, artist_path(art.artist_id) %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/arts/new.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        似顔絵登録＆削除フォーム
      </h1>
      <h2 class="subtitle">
         Welcome great caricature artist!
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="columns is-6">
        <%= form_with model: @art, url: arts_path, local: true do |f| %>
        <%= render 'shared/error_messages', model: @art %>

          <div class="field">
            <%= f.label :image, "似顔絵", class: "label" %>
            <%= f.attachment_field :image, class: "input is-success" %>
          </div>

          <div class="field is-grouped">
            <div class="control">
              <%= f.label :arttype_id, "この絵の種類", class: "label" %>
              <div class="select is-primary">
                <%= f.collection_select(:arttype_id, Arttype.all, :id, :name, {} )%>
              </div>
            </div>

            <div class="control">
              <%= f.label :arttouch_id, "この絵のタッチ", class: "label" %>
              <div class="select is-primary">
                <%= f.collection_select(:arttouch_id, Arttouch.all, :id, :name, {} )%>
              </div>
            </div>
          </div>

          <div class="field is-grouped is-grouped-centered">
            <%= f.submit "似顔絵登録", class: "button is-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @arts.each do |art| %>
        <% if current_artist.id == art.artist_id %>
          <div class="column is-6">
            <div class="card">
              <div class="card-content">
                <div class="card-image">
                  <figure class="image is-1by1">
                    <%= attachment_image_tag art, :image %>
                  </figure>
                </div>
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-content">
                    <div class="title"><%= link_to "削除", art_path(art.id), method: :delete %></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/homes/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <strong class="is-size-1" style="font-family: serif;">貴方の大切な人へ似顔絵をプレゼントしませんか？</strong>
        <br><br>
      </div>
    </div>
  </article>
  <br>
  <div class="content has-text-centered">
    <div class="title is-1" style="font-family: Arial Black;">10秒で</div>
    <div class="title is-3" style="font-family: Arial Black;">理想の似顔絵師をご紹介</div>
  </div>
  <div class="columns is-centered">
    <div class="column is-5">
      <br>
      <%= link_to "今すぐ診断を始める", matchings_path, class: "button is-large is-rounded is-danger is-fullwidth" %>
    </div>
  </div>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtistmatchApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%# <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" /> %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-dark">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: Arial Black;"><font color="white">Artist Match App</font></h1>
        <% end %>
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <div class="navbar-item">
            <%= link_to "似顔絵師さん一覧", artists_path, class: "button is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "似顔絵一覧", arts_path, class: "button is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "マッチング", matchings_path, class: "button is-light" %>
          </div>
        </div>
        <div class="navbar-end">
          <a class="navbar-item">
          似顔絵師さんはこちら<i class="fas fa-arrow-alt-circle-right"></i>
          </a>
          <% if artist_signed_in? %>
            <div class="navbar-item">
              <%= link_to "登録情報の編集", edit_artist_path(current_artist.id), class: "button is-light" %>
            </div>
            <div class="navbar-item">
              <%= link_to "絵の登録＆削除", new_art_path, class: "button is-light" %>
            </div>
            <div class="navbar-item">
              <%= link_to "ログアウト", destroy_artist_session_path, method: :delete, class: "button is-light" %>
            </div>
          <% else %>
            <div class="navbar-item">
              <%= link_to "ログイン", new_artist_session_path, class: "button is-light" %>
            <div class="navbar-item">
              <%= link_to "新規登録", new_artist_registration_path, class: "button is-light" %>
            </div>
          <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
    <section class="hero is-light">
      <div class="hero-body">
        <div class="container">
          <div class="content has-text-centered">
            <h3 class="title">
              似顔絵掲載協力
            </h3>
            <h6 class="subtitle">
              青木猿頬様/ジャッキィ様/川上奈々の似顔絵屋さん様/うません_似顔絵師様/ヤマダタカエ@似顔絵師様/ようこう@鉛筆画始めました様にご協力頂き掲載させて頂きました。<br>
              誠にありがとうございます。
            </h6>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/matchings/index.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マッチングページ
      </h1>
      <h2 class="subtitle">
         I hope I'll have a close relationship with artists!
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="content has-text-centered">
    <div class="title is-4">貴方の求める絵に近い絵をクリックして下さい</div>
  </div>
</section>

<div class="flex-box">
  <img id="left-image" src="https://pbs.twimg.com/media/Eodx2WeUUAAZYTV?format=jpg&name=large">
  <img id="right-image" src="https://pbs.twimg.com/media/EoSqRUbVQAAISrz?format=jpg&name=4096x4096">
</div>

<section class="section_1 hidden">
  <div class="container">
    <div class="columns is-multiline">
      <% @arts.each do |art| %>
        <% if art.arttype_id == 2 && art.arttouch_id == 3 %>
          <div class="column is-4">
            <div class="card">
              <div class="card-content">
                <div class="card-image">
                  <figure class="image is-1by1">
                    <%= link_to artist_path(art.artist.id) do %>
                      <%= attachment_image_tag art, :image %>
                    <% end %>
                  </figure>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

<section class="section_2 hidden">
  <div class="container">
    <div class="columns is-multiline">
      <% @arts.each do |art| %>
        <% if art.arttype_id == 2 && art.arttouch_id == 2 %>
          <div class="column is-4">
            <div class="card">
              <div class="card-content">
                <div class="card-image">
                  <figure class="image is-1by1">
                    <%= link_to artist_path(art.artist.id) do %>
                      <%= attachment_image_tag art, :image %>
                    <% end %>
                  </figure>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

<section class="section_3 hidden">
  <div class="container">
    <div class="columns is-multiline">
      <% @arts.each do |art| %>
        <% if art.arttype_id == 3 && art.arttouch_id == 3 %>
          <div class="column is-4">
            <div class="card">
              <div class="card-content">
                <div class="card-image">
                  <figure class="image is-1by1">
                    <%= link_to artist_path(art.artist.id) do %>
                      <%= attachment_image_tag art, :image %>
                    <% end %>
                  </figure>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

<section class="section_4 hidden">
  <div class="container">
    <div class="columns is-multiline">
      <% @arts.each do |art| %>
        <% if art.arttype_id == 3 && art.arttouch_id == 2 %>
          <div class="column is-4">
            <div class="card">
              <div class="card-content">
                <div class="card-image">
                  <figure class="image is-1by1">
                    <%= link_to artist_path(art.artist.id) do %>
                      <%= attachment_image_tag art, :image %>
                    <% end %>
                  </figure>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>